# Generated by Django 5.0.6 on 2024-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('rented', 'Арендован')], default='available', max_length=20),
        ),
    ]
