# Generated by Django 5.0.6 on 2024-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bicycle_price_alter_bicycle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_id', models.IntegerField()),
                ('bicycle_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('rental_cost', models.IntegerField()),
                ('rental_minute', models.FloatField()),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='rent_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
