# Generated by Django 5.0.6 on 2024-07-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_rentailhistory_bicycle_rent_start_bicycle_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentailhistory',
            name='rental_cost',
            field=models.FloatField(),
        ),
    ]
