# Generated by Django 5.0.6 on 2024-07-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_rentailhistory_rental_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentailhistory',
            options={'verbose_name': 'Журнал аренды велосипедов', 'verbose_name_plural': 'Журнал аренды велосипедов'},
        ),
    ]
