# Generated by Django 5.0.6 on 2024-07-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_alter_rentailhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
    ]
